### ISSUE TITLE
Vraagje

### ISSUE THREAD

**Issue by n9iels** [hans2103/pkg_SocialMetaTags#11]
Ha Hans,

Klein vraagje, op regel 87 van de system plugin staat de volgende code:
```
// Component specific overrides
if ($menu->getActive() == $menu->getDefault())
{
    // overrides for homepage
}
....
```
Wat was het idee hiervan? Het geeft namelijk best vaak errors op de homepage

**Comment by hans2103** [comment]
The intention was to provide alternate information on the frontpage. 
Due to the errors it seems better to remove this part for now. 
Will create a new version in a sec.
