### ISSUE TITLE
combination with Jsitemaps

### ISSUE THREAD

**Issue by superknutsel** [hans2103/pkg_SocialMetaTags#13]
On a website I have a sitemap that was not created (Jsitemaps).
So went on a search...

Through debug in Jsitemaps :
-Parsererror- SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

Then to the website :
https://www.xxxx.nl/index.php?option=com_jmap&view=sitemap&format=xml 
Getting this as a result :
Fatal error: Call to undefined method JDocumentXml::addCustomTag() in /home/yyyy/public_html/plugins/system/socialmetatags/socialmetatags.php on line 257

It was found on a Joomla 3.4.8 website that had the db collation set to utf8mb.
After disabling the socialmetatags plugin the sympthoms went away.....

**Comment by hans2103** [comment]
issue might be solved with release v1.4.4
please try the new version
