### ISSUE TITLE
Error with JSitemap xml 

### ISSUE THREAD

**Issue by wderuijter** [hans2103/pkg_SocialMetaTags#16]
Hey Hans, 

I ran into some problems with an older version of socialmetatags in combination with jsitemap pro on my sites. To be more specific, with JSitemaps' XML output.

I used to add some code in socialmetatags.php#31 to make sure the social metatags only get added for html documents. 
```
$doc = JFactory::getDocument();
if (!($doc instanceof JDocumentHTML)) {
    return;
}
```
or 

```
if (!($doc instanceof JDocumentHTML)) {
    return;
}
```
Iv'e only just found out your extension is available on github. Perhaps this is something to add to it.

**Comment by wderuijter** [comment]
Should this have been resolved in https://github.com/hans2103/pkg_SocialMetaTags/issues/13 ?

**Comment by hans2103** [comment]
I do think so it is solved in #13
Please try with the updated version of my SocialMetaTags plugin.

keep me informed please.

Op wo 25 mei 2016 om 12:08 schreef Wim de Ruijter <notifications@github.com

**Comment by wderuijter** [comment]
Hi @hans2103 , I've tried the updated version and it gives me a 500 error on JSitemap's xml sitemap. 
Disabling the socialmetatags system plugin resolves the error.

**Comment by hans2103** [comment]
issue should be solved with release v1.4.5
please update

**Comment by wderuijter** [comment]
Thanks Hans, I'll update this afternoon.

**Comment by n9iels** [comment]
There are still problems with `json` and `raw` format. When using the com_ajax interface and use json or raw as format you get a `Undifined method JDocument::addHeadLink()` error.

A solution for this can be:
```
$exclude = array('feed', 'xml', 'json', 'raw');
if (in_array($this->app->input->getCmd('format', ''), $exclude))
{
	return true;
}
```

**Comment by hans2103** [comment]
true... nice solution. Otherwise too many if-then-else constructions

Will apply it now. Release a  new version soon.

**Comment by wderuijter** [comment]
Isn't it possible to just check for html format?

**Comment by hans2103** [comment]
when format is html the page should render. 
But when you disable the SEF url and notice the weblink, you should not see format=html
format=html is the default output
