### ISSUE TITLE
Is this open source? Where is the license?

### ISSUE THREAD

**Issue by Flimm** [hans2103/pkg_SocialMetaTags#18]
It's not clear if this package is meant to be open source. Could you choose a license and apply it to this repo? Joomla is licensed under GPLv2 or later, so that is probably a good choice.

http://choosealicense.com/

**Comment by hans2103** [comment]
This Joomla! extension is meant to be open source. 
The license applied to it is GNU GPL version 3 and is mentioned in the head of every .php file. 

Just dived into the Joomla! documentation and noticed that you are absolutely right.
https://docs.joomla.org/Extensions_and_GPL/en

```
3. Provide a copy of the GPL license within your package:
- this file doesn't need to be installed with the extension, just included with the package as a text file
- There is a text available to copy and save has text file: [5]
```

**Comment by allrude** [comment]
"Cross your t’s and dot your i’s."  good work Hans

**Comment by hans2103** [comment]
added license in feature/Card18 with commit 77a918efd5e7f4f960884e45486cdcb1485778f9

**Comment by Flimm** [comment]
Wow, a wasn't expecting a response this quick! Nice!
