### ISSUE TITLE
Use article title, not contents of <title>

### ISSUE THREAD

**Issue by Flimm** [hans2103/pkg_SocialMetaTags#19]
My Joomla site has been configured like this: "Include Site Name in Page Titles" has been set to "Before". This gets saved to this line in `configuration.php`:

    public $sitename_pagetitles = '1';

The problem lies in the fact that this plug-in re-uses the website title in the meta tag for title:

    <meta property="og:title" content="WEBSITENAME - ARTICLE TITLE">

I would like for this to be simply the article's title, to follow Facebook's recommendations. Right now, I've changed the global settings `sitename_pagetitles`, but ideally, I wouldn't need to.

Thanks for your time!

**Comment by hans2103** [comment]
I can reproduce the issue... I did not stumbled upon this issue before since I always add the title of the site After. 
Will dive into the code to come with a fix.

**Comment by hans2103** [comment]
problem solved in release 1.4.7.1
https://github.com/hans2103/pkg_SocialMetaTags/releases/tag/v1.4.7.1

**Comment by Flimm** [comment]
That works a treat, thank you so much!
