### ISSUE TITLE
find Facebook url not working anymore

### ISSUE THREAD

**Issue by superknutsel** [hans2103/pkg_SocialMetaTags#26]
This url : http://findmyfacebookid.com/  is not working anymore.

**Comment by hans2103** [comment]
Thank you. Did you happen to find a solution yet?
Op di 31 jul. 2018 om 09:35 schreef Nico van Leeuwen <
notifications@github.com>

**Comment by superknutsel** [comment]
One that worked for me was https://commentpicker.com/find-facebook-id.php
But there are a lot of them :-)

**Comment by hans2103** [comment]
Fixed in new release https://github.com/hans2103/pkg_SocialMetaTags/releases/tag/v1.4.9
